version: '3.8'

services:
  grandpa-backend:
    container_name: 70-30-grandpa-backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - grandpa-db
      - grandpa-redis
    environment:
      - DEBUG=1
      - SECRET_KEY=changesecurekeyinproduction
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,grandpa-backend,[::1]
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=7030db
      - SQL_USER=7030user
      - SQL_PASSWORD=7030password
      - SQL_HOST=grandpa-db
      - SQL_PORT=5432
      - REDIS_URL=redis://grandpa-redis:6379/1

  grandpa-tests:
    container_name: 70-30-grandpa-tests
    build: ./backend
    command: pytest
    volumes:
      - ./backend:/app
    depends_on:
      - grandpa-db
      - grandpa-redis
    environment:
      - DEBUG=1
      - SECRET_KEY=changesecurekeyinproduction
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=7030db
      - SQL_USER=7030user
      - SQL_PASSWORD=7030password
      - SQL_HOST=grandpa-db
      - SQL_PORT=5432
      - REDIS_URL=redis://grandpa-redis:6379/1

  grandpa-client:
    container_name: 70-30-grandpa-client
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8001/api

  grandpa-db:
    container_name: 70-30-grandpa-db
    image: postgis/postgis:15-3.3
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=7030user
      - POSTGRES_PASSWORD=7030password
      - POSTGRES_DB=7030db
    ports:
      - "5435:5432"

  grandpa-redis:
    container_name: 70-30-grandpa-redis
    image: redis:7-alpine
    ports:
      - "6381:6379"
